//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.newDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class recentNew
    {
        public int newsNumber { get; set; }
        public string picture { get; set; }
        public string pictureDescription { get; set; }
        public string pictureDate { get; set; }
        public string description { get; set; }
        public string date { get; set; }
        public string news { get; set; }
    }
}
